### ISSUE TITLE
Support for workspace

### ISSUE THREAD

**Issue by vim-zz** [cmyr/cargo-instruments#1]
I am trying to run agains a binary which is part of a workspace, it fails with this message: 

```
manifest path `/path/to/project/root/Cargo.toml` is a virtual manifest, but this command requires running against an actual package in this workspace
```

How should I proceed?

Thanks!

**Comment by cmyr** [comment]
The current directory has to contain a Cargo.toml file that defines a binary target, so if you're in a workspace you may need to run the command from the subcrate that defines the binary. Otherwise, though, this should work.

I was just playing around and this was working for me, but there are definitely bugs to shake out, so please let me know if you have any problems!

**Comment by vim-zz** [comment]
Ok, I am trying to run from the application crate inside the workspace, and I get this error:

```
    Finished dev [unoptimized + debuginfo] target(s) in 1.16s
No such file or directory (os error 2)
```

Should I have something specific in the Cargo.toml?

**Comment by cmyr** [comment]
@vim-zz hmm, I published a new version yesterday, try that?

**Comment by vim-zz** [comment]
it works!

i run it from the application sub directory under the workspace with `--bin` flag pointing my app name
